spring:
  application:
    name: admin-client
  security:
    user:
      name: admin
      password: admin
#  boot:
#    admin:
#      client:
#        url: http://localhost:8769
#        instance:
#          name: admin-client
#          metadata: # 这个name与password用于在注册到管理端时，使管理端有权限获取客户端端点数据
#            user.name: ${spring.security.user.name}
#            user.password: ${spring.security.user.password}

#  boot:
#    admin:
#      client:
#        url: http://localhost:8769
server:
  port: 8767


eureka:
  instance:
    prefer-ip-address: true
    #发送心跳给server的频率，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 1
    #Server从收到client后，下一次收到心跳的间隔时间。超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 1
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 8
    health-check-url-path: /actuator/health

  #eureka:
  #  client:
  #    registryFetchIntervalSeconds: 5
  #    service-url:
  #      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  #  instance:
  #    leaseRenewalIntervalInSeconds: 10
  #    health-check-url-path: /actuator/health
  #    preferIpAddress: true
  #    lease-expiration-duration-in-seconds: 30


  # lease-expiration-duration-in-seconds: 30 # 续约到期时间（默认90秒

#eureka:
#  client:
#    registryFetchIntervalSeconds: 5
#    service-url:
#      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
#    healthcheck:
#      enabled: true
#    register-with-eureka: true #是否注册到eureka服务器
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    lease-renewal-interval-in-seconds: 10
#    preferIpAddress: true
#    health-check-url-path: /actuator/health


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
