spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: pwd
#  cloud:
#    config:
#      uri: ${CONFIG_SERVER_URL:http://localhost:8888}


server:
  port: 8761


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false # 设为false，关闭自我保护
    prefer-ip-address: true
    eviction-interval-timer-in-ms: 5000 # 清理间隔（单位毫秒，默认是60*1000）启用主动失效，并且每次主动失效检测间隔为3s


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS